export const bibleVersions = [
  //   { name: 'Authorized (King James) Version', id: 240, abbreviation: 'AKJV' },
  //   { name: 'Amplified Bible', id: 45, abbreviation: 'AMP' },
  //   { name: 'Amplified Bible, Classic Edition', id: 52, abbreviation: 'AMPC' },
  //   { name: 'American Standard Version', id: 8, abbreviation: 'ASC' },
  //   { name: 'BRG Bible', id: 128, abbreviation: 'BRG' },
  //   { name: 'Common English Bible', id: 105, abbreviation: 'CEB' },
  //   { name: 'Contemporary English Version', id: 46, abbreviation: 'CEV' },
  //   { name: 'Complete Jewish Bible', id: 195, abbreviation: 'CJB' },
  //   { name: 'Christian Standard Bible', id: 251, abbreviation: 'CSB' },
  { name: 'Darby Translation', id: 16, abbreviation: 'DARBY' },
  //   { name: 'Disciples’ Literal New Testament', id: 123, abbreviation: 'DLNT' },
  //   { name: 'Douay-Rheims 1899 American Edition', id: 63, abbreviation: 'DRA' },
  //   { name: 'Evangelical Heritage Version', id: 257, abbreviation: 'EHV' },
  //   { name: 'Easy-to-Read Version', id: 173, abbreviation: 'ERV' },
  //   { name: 'English Standard Version', id: 47, abbreviation: 'ESV' },
  //   {
  //     name: 'English Standard Version Anglicised',
  //     id: 166,
  //     abbreviation: 'ESVUK',
  //   },
  //   { name: 'Expanded Bible', id: 233, abbreviation: 'EXB' },
  //   { name: 'Good News Translation', id: 86, abbreviation: 'GNT' },
  //   { name: '1599 Geneva Bible', id: 236, abbreviation: 'GNV' },
  //   { name: 'GOD’S WORD Translation', id: 158, abbreviation: 'GW' },
  //   { name: 'Holman Christian Standard Bible', id: 77, abbreviation: 'HCSB' },
  //   { name: 'International Children’s Bible', id: 232, abbreviation: 'ICB' },
  //   { name: 'International Standard Version', id: 124, abbreviation: 'ISV' },
  //   { name: 'Jubilee Bible 2000', id: 245, abbreviation: 'JUB' },
  //   { name: '21st Century King James Version', id: 48, abbreviation: 'KJ21' },
  { name: 'King James Version', id: 9, abbreviation: 'KJV' },
  //   { name: 'Lexham English Bible', id: 165, abbreviation: 'LEB' },
  //   { name: 'Modern English Version', id: 126, abbreviation: 'MEV' },
  //   {
  //     name: 'Mounce Reverse-Interlinear New Testament',
  //     id: 217,
  //     abbreviation: 'MOUNCE',
  //   },
  //   { name: 'Names of God Bible', id: 239, abbreviation: 'NOG' },
  //   {
  //     name: 'New American Bible (Revised Edition)',
  //     id: 115,
  //     abbreviation: 'NABRE',
  //   },
  //   { name: 'New American Standard Bible', id: 49, abbreviation: 'NASB' },
  //   { name: 'New Century Version', id: 78, abbreviation: 'NCV' },
  //   { name: 'New English Translation', id: 234, abbreviation: 'NET' },
  //   { name: "New International Reader's Version", id: 76, abbreviation: 'NIRV' },
  //   { name: 'New International Version', id: 31, abbreviation: 'NIV' },
  //   { name: 'New International Version - UK', id: 64, abbreviation: 'NIVUK' },
  //   { name: 'New King James Version', id: 50, abbreviation: 'NKJV' },
  //   { name: 'New Living Translation', id: 51, abbreviation: 'NLT' },
  //   { name: 'New Life Version', id: 74, abbreviation: 'NLV' },
  //   { name: 'New Matthew Bible', id: 250, abbreviation: 'NMB' },
  //   { name: 'New Revised Standard Version', id: 210, abbreviation: 'NRSV' },
  //   {
  //     name: 'New Revised Standard Version, Anglicised',
  //     id: 211,
  //     abbreviation: 'NRSVA',
  //   },
  //   {
  //     name: 'New Revised Standard Version, Anglicised Catholic Edition',
  //     id: 213,
  //     abbreviation: 'NRSVACE',
  //   },
  //   {
  //     name: 'New Revised Standard Version Catholic Edition',
  //     id: 212,
  //     abbreviation: 'NRSVCE',
  //   },
  //   { name: 'New Testament for Everyone', id: 129, abbreviation: 'NTE' },
  //   { name: 'Orthodox Jewish Bible', id: 228, abbreviation: 'OJB' },
  //   { name: 'J.B. Phillips New Testament', id: 164, abbreviation: 'PHILLIPS' },
  //   { name: 'Revised Geneva Translation', id: 271, abbreviation: 'RGT' },
  //   { name: 'Revised Standard Version', id: 214, abbreviation: 'RSV' },
  //   {
  //     name: 'Revised Standard Version Catholic Edition',
  //     id: 215,
  //     abbreviation: 'RSVCE',
  //   },

  //   { name: 'Tree of Life Version', id: 146, abbreviation: 'TLV' },
  //   { name: 'The Passion Translation', id: 256, abbreviation: 'TPT' },
  //   { name: 'The Voice', id: 237, abbreviation: 'VOICE' },
  //   { name: 'Worldwide English (New Testament)', id: 73, abbreviation: 'WE' },
  //   { name: 'World English Bible', id: 235, abbreviation: 'WEB' },
  //   { name: 'Wycliffe Bible', id: 53, abbreviation: 'WYC' },
  { name: "Young's Literal Translation", id: 15, abbreviation: 'YLT' },
];
